version: 2
jobs:
  build:
    working_directory: ~/tests
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            mkdir test-results
            python tests.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1